version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./mongo-data:/data/db
    networks:
      - my-network

  tutorials-api:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
