name: Publish Docker Image

on:
  push:
    branches: [main]

jobs:
  tests:
      runs-on: ubuntu-latest
      strategy:
      matrix:
        node: [ 14, 16, 18 ]
      steps:
        - name: Checkout from main
          uses: actions/checkout@v3
          with:
            ref: main
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node }}
        - name: Install deps
          run: npm ci
        - name: Run unit tests
          run: npm run test
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Publish to the registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: https://ghcr.io
          name: https://ghcr.io/maksym-bezditko/tutorials/tutorials
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "development"